0.2.x
typhoon-php/type-stringifier pull request #4
Opened 2023-03-04 23:46 UTC by aivchen

2023-03-04 23:50 UTC, vudaltsov requested changes

2023-03-04 23:50 UTC, vudaltsov commented on src/TypeStringifier.php
> +        if ($type->valueType instanceof MixedType) {
`$type->valueType === types::mixed` и так везде ниже проверям atomic типы.

2023-03-04 23:51 UTC, vudaltsov commented
Change the PR name, please.

2023-03-04 23:53 UTC, vudaltsov commented
And it seems that locally you've committed directly to `0.2.x` instead of creating a separate branch. Fix that, otherwise you will have problems with pulling later. If you have problems with that, let me know.

2023-03-05 08:35 UTC, aivchen commented on src/TypeStringifier.php
> +        if ($type->valueType instanceof MixedType) {
In this case we get a psalm error:
```bash
Type ExtendedTypeSystem\Type<mixed> for $type->valueType is never =enum(ExtendedTypeSystem\Type\MixedType::self) (see https://psalm.dev/056)
        if ($type->valueType === types::mixed) {
```

2023-03-05 15:52 UTC, vudaltsov commented on src/TypeStringifier.php
> +        if ($type->valueType instanceof MixedType) {
Ok!

2023-03-05 15:53 UTC, vudaltsov approved these changes

2023-03-05 15:53 UTC, merged

2023-03-05 15:54 UTC, vudaltsov commented
Thank you, @aivchen!

2023-03-11 19:09 UTC, luckycrocodile2261 commented
Hi, @aivchen.
Did you checked my code?